name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
          
jobs:
  humble-devel-ci:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.0
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Install requirements
        run: pip3 install requests
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.3.3
        with:
          package-name: mocap_optitrack_driver
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "https://raw.githubusercontent.com/MOCAP4ROS2-Project/mocap4ros2_optitrack/main/dependency_repos.repos"
          skip-tests: false
